### PR TITLE
Missing use Laravel\Passport\Passport

### PR DESCRIPTION
**Pull request by csgt**
We need to add the use directive in order to use Passport::refreshTokensExpireIn();  instead of hardcoding the date.

### CODE REVIEW

**Comment by csgt** [comment]
I was banging my head on why this would create my user, give me correct access tokens and got an Unauthenticated error after the first request.  It was because my id column on my User model is not "id", but "userid".  With this change, the user is able to configure the name of the id column, by default leaving it in "id" for backwards compatibility.

**Comment by csgt** [comment]
Also, please update your packagist dependencies, as the last version available is 1.4.1.  Thanks

**Comment by MMasterson** [comment]
@csgt does this fix a problem I am receiving at install

`Target [League\OAuth2\Server\Repositories\ClientRepositoryInterface] is not  
   instantiable while building [League\OAuth2\Server\AuthorizationServer].` 

if not, do you have any suggestions? 

sorry to comment here, there's just no issues tab

**Comment by Jono20201** [comment]
Fixed in `2.0.0`? Can be closed?

**Comment by danjdewhurst** [comment]
@Jono20201 does this need merging still?

**Comment by Jono20201** [comment]
Looking into it further this is actually something totally different than the title suggests. 

However, I fixed "Missing use Laravel\Passport\Passport" in #6

**Comment by danjdewhurst** [comment]
@Jono20201 Thank you. I've been very busy lately and haven't had much time to keep track of things here. I've opened the issues tab now, so do you mind opening an issue there so I can close this? If you're interested I'd be happy to give you access to contribute.

**Comment by Jono20201** [comment]
@danjdewhurst 

Am I not sure there is anything to make an issue about? I think @csgt may want to create a new PR with the feature he is suggesting, instead of merging multiple suggestions into a single PR (which may have just occurred as he is merging in his master fork of this repo?

More than happy to be an active contributor on this repo, we're using it in our project, so I am reliant on it working 😄

**Comment by danjdewhurst** [comment]
@Jono20201 I see! I'll close this then and sort out your permissions shortly. Thanks again.

**Comment by csgt** [comment]
This PR was to make the userid column configurable as well, since the current code expects the column to be named "id".  With this PR, the column id is configurable as the other variables.  I missed adding the use Passport, so I added both on the same PR.  Please check or tell me if I need to do another PR

**Comment by Jono20201** [comment]
Would it not possibly be better to use the `->getKey()` method provided by Laravel's Models?

**Comment by Jono20201** [comment]
I've made a PR (#9) for the above.

**Pull request closed without merging**
